# -*- coding: utf-8 -*-
"""GPT bac_timeweb ALDAN Segmenter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_U7CmWKaC74unwNU5bp9ZlOGo0W-8ocj
"""

# =========================
# FASTAPI BACKEND (DEPLOY VERSION FOR SERVER / TIMEWEB)
# =========================

import io
import os
import cv2
import json
import time
import base64
import numpy as np
from PIL import Image
from fastapi import FastAPI, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from ultralytics import YOLO

# -------------------------
# CONFIG
# -------------------------
MODEL_NAME = os.getenv("YOLO_SEG_MODEL", "yolov8m-seg.pt")

# -------------------------
# INIT
# -------------------------
app = FastAPI(title="YOLOv8 Segmentation API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

print("Loading model:", MODEL_NAME)
model = YOLO(MODEL_NAME)
CLASS_NAMES = model.names

PALETTE = [
    (255,56,56),(255,157,151),(255,112,31),(255,178,29),(207,210,49),
    (72,249,10),(146,204,23),(61,219,134),(26,147,52),(0,212,187),
    (44,153,168),(0,194,255),(52,69,147),(100,115,255),(0,24,236),
    (132,56,255),(82,0,133),(203,56,255),(255,149,200),(255,55,199)
]

# -------------------------
# ROUTES
# -------------------------
@app.get("/")
def root():
    return {"status": "ok"}

@app.get("/health")
def health():
    return {"status": "ok"}

@app.options("/segment")
async def options_segment():
    return {"ok": True}

# -------------------------
# UTILS
# -------------------------
def to_bgr(pil):
    return cv2.cvtColor(np.array(pil), cv2.COLOR_RGB2BGR)

def to_base64(img):
    ok, buf = cv2.imencode(".png", img)
    if not ok:
        raise RuntimeError("encode error")
    return base64.b64encode(buf.tobytes()).decode()

# -------------------------
# MAIN ENDPOINT
# -------------------------
@app.post("/segment")
async def segment_image(
    image: UploadFile = File(...),
    classes: str = Form("person,car"),
    mask_colors: str = Form(None)
):
    try:
        img_bytes = await image.read()
        pil = Image.open(io.BytesIO(img_bytes)).convert("RGB")
        frame = to_bgr(pil)

        # parse colors from frontend
        color_map = {}
        if mask_colors:
            try:
                data = json.loads(mask_colors)
                for k, v in data.items():
                    if isinstance(v, list) and len(v) == 3:
                        r, g, b = v
                        color_map[k.lower()] = (b, g, r)
            except:
                pass

        # segmentation
        t0 = time.time()
        res = model.predict(frame, verbose=False)[0]
        seg_time = round(time.time() - t0, 3)

        out = frame.copy()

        if res.masks is not None:
            masks = res.masks.data.cpu().numpy()
            ids = res.boxes.cls.cpu().numpy()

            for i in range(len(masks)):
                m = masks[i].astype(bool)
                cls_id = int(ids[i])
                name = CLASS_NAMES[cls_id].lower()
                color = color_map.get(name, PALETTE[cls_id % len(PALETTE)])
                out[m] = color

        result_b64 = to_base64(out)

        # RESPONSE STRICT FOR FRONTEND
        return {
            "segmented_image": result_b64,
            "segmentation_time_sec": seg_time
        }

    except Exception as e:
        return {
            "segmented_image": None,
            "error": str(e)
        }


# -------------------------
# RUN (for server)
# -------------------------
# запуск:
# uvicorn main:app --host 0.0.0.0 --port 8000